version: '3'
services:
  server:
    build:
      dockerfile: server/Dockerfile
      context: .
      args:
        NODE_ENV: development
    env_file: server/.env
    volumes:
      - ./server :/app/server
    entrypoint: ["yarn", "run", "start:dev"]
    ports:
      - "8050:80"

  frontend:
    build: 
      dockerfile: frontend/Dockerfile
      context: .
    volumes:
      - type: bind
        source: ./frontend
        target: /app/frontend
    ports:
      - "5173:5173"